In [17]:
import numpy as np
from numpy import linalg as LA
import pandas as pd

Create the Matrix A

In [18]:
I = np.eye(3) # 3x3 identity matrix
A = np.array([
    [6,-4,-8],
    [-3,10,11],
    [2,-4,-4]
    ])
print(A)


[[ 6 -4 -8]
 [-3 10 11]
 [ 2 -4 -4]]


Compute A^10

In [19]:
# A_Raised = A^10
A_10 = np.linalg.matrix_power(A,10)
print(A_10)

[[ 31281152 -60465152 -91745280]
 [-59941376 120931328 180871680]
 [ 30232576 -60465152 -90696704]]


Compute (A/6) ^ 10

In [20]:
A_Div6 = np.linalg.matrix_power((A/6),10)
print(A_Div6)

[[ 0.51733306 -0.99998306 -1.51729919]
 [-0.99132077  1.99998306  2.9912869 ]
 [ 0.49999153 -0.99998306 -1.49995766]]


Explore what happens when A is powered up even higher by increasing the exponent. What do
you notice when you compare different high powers of A/6?

In [38]:
# for i in range(10):
#     print("A^" + str(i+10))
#     print( (A//6)^(i+10))

for i in range(10,110,10):
    print("A^" + str(i))
    print(np.linalg.matrix_power((A/6),i))

A^10
[[ 0.51733306 -0.99998306 -1.51729919]
 [-0.99132077  1.99998306  2.9912869 ]
 [ 0.49999153 -0.99998306 -1.49995766]]
A^20
[[ 0.50030073 -1.         -1.50030073]
 [-0.99984964  2.          2.99984963]
 [ 0.5        -1.         -1.5       ]]
A^30
[[ 0.50000522 -1.         -1.50000522]
 [-0.99999739  2.          2.99999739]
 [ 0.5        -1.         -1.5       ]]
A^40
[[ 0.50000009 -1.         -1.50000009]
 [-0.99999995  2.          2.99999995]
 [ 0.5        -1.         -1.5       ]]
A^50
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]
A^60
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]
A^70
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]
A^80
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]
A^90
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]
A^100
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]


Answer: Every columns become proportional to the same vector
        All colums converge to the eigenvector corresponding to the largest eigenvalue

Question: What is the relationship between the columns of high powers of A/6?

Answer: All Columns become multiples of the same eigenvector

3. Create a vector x that is equal to the first column of some high power of A/6.

In [39]:
B = np.linalg.matrix_power((A/6),100)
x = B[:3,1]
print("B: ")
print(B)
print()

print("x: ")
print(x)
print()

print("Ax: ")
print(A@x)



B: 
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]

x: 
[-1.  2. -1.]

Ax: 
[-6. 12. -6.]


Q3. Is the column vector x an eigenvector? What is it's eigenvalue?
    
    Answer: Yes the vector is an eigenvector of A, and the associated eigenvalue is approximately 6.

EigenValues of A

In [23]:
A
# Eigenvalues and vectors
# vals,vecs = LA.eig(A)
vals,vecs = np.linalg.eig(A)
print(A)
print(vals)
print(vecs)

[[ 6 -4 -8]
 [-3 10 11]
 [ 2 -4 -4]]
[2. 4. 6.]
[[-5.77350269e-01  8.94427191e-01 -4.08248290e-01]
 [ 5.77350269e-01  4.47213595e-01  8.16496581e-01]
 [-5.77350269e-01  1.43267576e-15 -4.08248290e-01]]
