In [17]:
import numpy as np
from numpy import linalg as LA
import pandas as pd

def companion_matrix(coeffs):
    n = len(coeffs) - 1
    C = np.zeros((n,n))
    C[range(1,n), range(n-1)] = 1 #subdiagonal of 1s
    C[:, -1] = -np.array(coeffs[:0:-1]) # last col = -[a_{n-1},...,a_0]     -np is required for proper ordering
    return C

1. Find the companion matrices for the following polynomials.

a) p(t)=t^2+2t-4

b) p(t)=t^3-9t^2 +12t+22

c) p(t)=t^4-2t^3 - 13t^2 +14t +24

d) Find the characteristic polynomials of the matrices you just found in parts a-c.

In [18]:
p_a = [1, 2, -4]
C_a = companion_matrix(p_a)
print("Companion matrix for p(t) = t^2 +2t - 4:\n", C_a)

print()

p_b = [1, -9, 12, 22]
C_b = companion_matrix(p_b)
print("Companion matrix for p(t) = t^3 -9t^2 +12t + 22:\n", C_b)

print()

p_c = [1, -2, -13, 14, 24]
C_c = companion_matrix(p_c)
print("Companion matrix for p(t) = t^4 -2t^3 -13t^2 + 14t + 24:\n", C_c)

char_a = np.poly(C_a)
char_b = np.poly(C_b)
char_c = np.poly(C_c)

print()
print("Characteristic polynomial of C_a:", char_a)
print("Characteristic polynomial of C_b:", char_b)
print("Characteristic polynomial of C_c:", char_c)


Companion matrix for p(t) = t^2 +2t - 4:
 [[ 0.  4.]
 [ 1. -2.]]

Companion matrix for p(t) = t^3 -9t^2 +12t + 22:
 [[  0.   0. -22.]
 [  1.   0. -12.]
 [  0.   1.   9.]]

Companion matrix for p(t) = t^4 -2t^3 -13t^2 + 14t + 24:
 [[  0.   0.   0. -24.]
 [  1.   0.   0. -14.]
 [  0.   1.   0.  13.]
 [  0.   0.   1.   2.]]

Characteristic polynomial of C_a: [ 1.  2. -4.]
Characteristic polynomial of C_b: [ 1. -9. 12. 22.]
Characteristic polynomial of C_c: [  1.  -2. -13.  14.  24.]


The characteristic polynomial gives back the original polynomial that was used to construct it.
By defnition the companion matrix: det(C - I_n) = (-1)^n p(λ) 
The eigenvalues of the companion matrix are exactly the roots of the polynomial

2. Show that the characteristic polynomial of a companion matrix for the n
th degree polynomial p(t) is det(C - I_n) = (-1)^n p(λ)  as follows. 
a) Show that if C is the companion matrix for a quadratic polynomial p(t)= t^2 +at+a_0, then det(C - I_n) = (-1)^n p(λ) by direct computation.

b) Use mathematical induction to show that the result holds for n ≥ 2 . Hint: expand the necessary determinant by cofactors down the first column.

a. 
Let p(t) = t^2 +at+a_0

Companion Matrix = C = [[0 -a0
                         1 -a1]]

Then:              C -λI_2 = [[-λ  -a0
                                1  -a1 - λ]]

Determinant:

                det(C -λI_2) = (-λ)(-a1 - λ) - (-a0)(1)
                             = λ(λ + a1) + a0
                             = λ^2 + a1λ +a0 = p(λ)

for n = 2: det(C -λI_n) = p(λ) = (-1)^2 p(λ)

b. 
Base Case: n = 2
proven in a.

Assume the result holds for degree n -1: det(C_n-1 -λI_n-1) = (-1)^n-1 p_n-1(λ)

where C_n-1 is the (n - 1) x (n - 1) companion matrix

Inductive Step:
For degree n, the companion matrix is:

C =  [[ 0.   0 ... 0 -a0]
     [  1.   0 ... 0 -a1]
     [  0.   1 ... 0 -a2]
     [  0.   0 ... 1 -a_n-1]]

Then C-λI = [[ -λ.   0 ... 0 -a0]
            [   1.  -λ ... 0 -a1]
            [   0.   1 ... 0 -a2]
            [   0.   0 ... 1 -a_n-λ]]

Step 1: Expand along the first Column
        det(C -λI_n) = (-λ)det(M_1) + (-1)^(2+1) (1) det(M_2)

Where:
- M_1 is the (n - 1) x (n - 1) matrix after removing first row and first column.
- M_2 is the (n - 1) x (n - 1) matrix after removing secound row and first column.

Cofactor expandsion:

You get a recursion: det(C_n -λI_n) = (-λ)det(C_n-1 -λI_n-1) - a0

Expanding recursively reproduces the polynomial: 

det(C_n -λI_n) = (-1)^n (λ^n + a_n-1 λ^n-1+...+a0) = (-1)^n p(λ)


In [21]:
# p_t = [1, 1, 1]
# C_t = companion_matrix(p_t)
# print("Companion matrix for p(t) = t^2 +at+a_0 :\n", C_t)
# print("det(p(t)):\n", np.linalg.det(C_t))

3. Suppose A is a nxn matrix. Let A = Q0 R0 be a QR factorization of A, and Create A_1 = R0 Q0. Let A1 = Q1 R1 be a QR factorization of A1 and create A2 = R1 Q1.

a). Show that A = Q0 A1 Q0^T

We know that A1 = R0Q0, Q0 is orthogonal, R0 is upper triangular

Then: Q0 A1 Q0^T = Q0 (R0 Q0) Q0^T = Q0R0(Q0Q0^T)

Since Q0 is orthogonal: Q0Q0^T = I

Thus: Q0 A1 Q0^T = Q0R0I = Q0R0 = A



b). Show that A = (Q0Q1) A2 (Q0Q1)^T

From part a). A = Q0 A1 Q0^T = Q0(Q1R1)Q0^T
              A = (Q0Q1)R1Q1Q0^T

Notice A2 = R1Q1, Therefore: A = (Q0Q1)A2(Q0Q1)^T

c). Show that (Q0Q1) is an orthogonal matrix

A matrix Q is orthogonal is Q^TQ = I
Both Q0 and Q1 are orthogonal (Q0^T Q0 =Q1^T Q1 = I)

Then: (Q0Q1)^T (Q0Q1) = Q1^T Q0^T Q0 Q1 = Q1^T Q1 = I

So Q0Q1 is orthogonal

d). Show that A, A1, and A2 all have the same eigenvalues.

Two Matrices B and C are similar if B = PCP^-1. 

From Part (a):
    A = Q0 A1 Q0^T

Since Q0 is orthogonal, Q0^-1 = Q0^T 

From part (b): A = (Q0Q1)A2(Q0Q1)^T

Similarly, Q0Q1 is orthogonal, so A and A2 are similar. Hence A, A1, A2 all have the same eigenvalues.




4. Approximate the roots of the polynomials in Question 1 by applying the QR Method to their companion matrices. Iterate until the entries below the main diagonal are all below 0.1

QR Methods to companion matrices: C_a, C_b, C_c

In [23]:
def qr_eigenvalues(A, tol=0.1,max_iter=1000):
    
    n = A.shape[0]
    Ak = A.copy()
    for i in range(max_iter):
        Q, R = np.linalg.qr(Ak)
        Ak = R @ Q
        # Check subdiagonal entries
        if np.all(np.abs(np.tril(Ak, -1)) < tol):
            break
    return np.diag(Ak), Ak # approximate eigenvalues, final matrix

#Apply to all companion matrices
eig_a, final_a = qr_eigenvalues(C_a)
eig_b, final_b = qr_eigenvalues(C_b)
eig_c, final_c = qr_eigenvalues(C_c)

print("Approximate roots of p_a:", eig_a)
print("Approximate roots of p_b:", eig_b)
print("Approximate roots of p_c:", eig_c)

Approximate roots of p_a: [-3.27868852  1.27868852]
Approximate roots of p_b: [ 6.91708587  3.10313866 -1.02022453]
Approximate roots of p_c: [ 3.87534711 -2.86638472  1.99080684 -0.99976923]
